import socket

print(" *** SERVIDOR TCP SOCKET *** ")

# INFORMAÇÕES DE CONFIGURAÇÃO
HOST = "INFORME AQUI O SEU IP" # informe o IP do servidor 
PORT = 12345
CODE = "utf-8"

# VARIAVEL DE INFORMAÇÕES DE ENDEREÇO E PORTA
INFO = (HOST,PORT)

# CRIANDO O SERVIDOR TCP SOCKET
SERVIDOR_TCP_SOCKET = socket.socket(socket.AF_INET,socket.SOCK_STREAM)

# INICIANDO CONEXÃO PARA A ESCUTA
SERVIDOR_TCP_SOCKET.bind(INFO)

# DETERMINANDO QUANTIDADE DE CONEXOES 
SERVIDOR_TCP_SOCKET.listen(1)

# IMPRIMINDO INFORMAÇÕES ...
print(f"SERVIDOR RECEBENDO MENSAGENS.... \n\n")

# LOOP DA CONEXÃO:
while True:
    CONEXAO,CLIENTE = SERVIDOR_TCP_SOCKET.accept()
    # ACEITANDO CONEXÕES ...
    print(f"\n CONECTANDO AO CLIENTE: {CLIENTE}") 
    # INFORMANDO CONEXÃO ...

    # LOOP DA COMUNICAÇÃO:
    for indice in range(5): # DEFININDO QUANTIDADES DE LOOPS DA TROCA DE MENSAGENS ENTRE O CLIENTE E O SERVIDOR
        MENSAGEM = CONEXAO.recv(1024)
        # OBS: SERVIDOR ESTA RECEBENDO MENSAGENS EM BYTES
        
        # IMPRIMINDO MENSAGEM RECEBIDA DO CLIENTE 
        print(CLIENTE,MENSAGEM.decode(CODE))

        MENSAGEN_RESPOSTA = MENSAGEM
        # MENSAGEN_RESPOSTA RECEBE A VARIAVEL MENSAGEM,
        # QUE CONTEM AS INFORMAÇÕES RECEBIDAS NA CONEXÃO COM O CLIENTE 

        CONEXAO.send(MENSAGEN_RESPOSTA)
        # CONEXÃO ENVIA MENSAGEM_RESPOSTA DE VOLTA PARA O CLIENTE

    # IMPRIMINDO INFORMAÇÕES ...
    print(f"\n FINALIZANDO ENVIO DE MENSAGENS",CLIENTE)

    # ENCERRANDO CONEXÃO COM CLIENTE  
    CONEXAO.close() 
    


